version: '3'

services:
  web:
    build: ./services/nginx
    image: ${OPENRESTYREPO}
    ports:
      - 80:80
      - 443:443
    links: 
      - php-fpm
    restart: always
    volumes:
      - ./services/nginx/src:/var/www/html

  php-fpm:
      build: ./services/php
      image: ${PHPREPO}
      volumes:
      - ./services/nginx/src:/var/www/html
