version: '3'

services:
  web:
    build: ./services/nginx
    image: 448067628045.dkr.ecr.us-east-2.amazonaws.com/myopenresty:latest
    ports:
      - 80:80
      - 443:443
    links: 
      - php-fpm
    restart: always
    volumes:
      - ./services/nginx/src:/var/www/html

  php-fpm:
      build: ./services/php
      image: 448067628045.dkr.ecr.us-east-2.amazonaws.com/myphp:latest
      volumes:
      - ./services/nginx/src:/var/www/html
