version: '3'

networks:
  web-network:

services:
  web:
    build: ./nginx
    image: myopenresty
    ports:
      - 80:80
      - 443:443
    links: 
        - php-fpm
    restart: always
    networks:
      - web-network

  php-fpm:
      build: ./php
      image: myphp
      networks:
      - web-network
     # volumes:
     # - ./php/src:/usr/local/openresty/nginx/html:ro
   
